@extends('layouts.dashboard')
@section('title', 'Active User Analytics')
@section('content')
    <style>
        .card-custom {
            border-radius: 1rem;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
            overflow: hidden;
            height: 100%;
        }

        .card-header-custom {
            background-color: #f8f9fa;
            padding: 1rem;
            font-weight: 600;
            color: #343a40;
            font-size: 1.1rem;
        }

        .card-body-custom {
            padding: 2rem;
            text-align: center;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 2rem;
            font-weight: bold;
        }

        .bg-pink {
            background-color: #e91e63;
            color: white;
        }

        .bg-dark-custom {
            background-color: #343a40;
            color: white;
        }

        .bg-success-custom {
            background-color: #28a745;
            color: white;
        }

        .card-footer-custom {
            background-color: #f8f9fa;
            color: #6c757d;
            padding: 0.75rem 1rem;
            font-size: 0.9rem;
        }
    </style>
    <div class="container mt-4">
        <h2>Analytics Dashboard</h2>
        <div class="d-flex mb-4 gap-2">
            <a href="{{ route('admin.analytics.export', ['type' => 'active']) }}" class="btn btn-success">
                Export Active Users
            </a>
            <a href="{{ route('admin.analytics.export', ['type' => 'inactive']) }}" class="btn btn-danger">
                Export Inactive Users
            </a>
        </div>
        <div class="row mb-4">
            <!-- Card 1 -->
            <div class="col-md-4">
                <div class="card card-custom">
                    <div class="card-header card-header-custom">
                        Total Exhibitor
                    </div>
                    <div class="card-body card-body-custom bg-pink">
                        {{ $usersWithPaidApps }}
                    </div>
                    <div class="card-footer card-footer-custom">
                        Total Exhibitor
                    </div>
                </div>
            </div>

            <!-- Card 2 -->
            {{-- <div class="col-md-4">
                <div class="card card-custom">
                    <div class="card-header card-header-custom">
                        Invitation Letters Generated
                    </div>
                    <div class="card-body card-body-custom bg-dark-custom">
                        {{ $invitationLetterCount }}
                    </div>
                    <div class="card-footer card-footer-custom">
                        Total Invitation Letters Generated by Exhibitor and Co-Exhibitor
                    </div>
                </div>
            </div> --}}

            <!-- Card 3 -->
            <div class="col-md-4">
                <div class="card card-custom">
                    <div class="card-header card-header-custom">
                        Extra Order Users
                    </div>
                    <div class="card-body card-body-custom bg-success-custom">
                        {{ $uniqueExtraOrder }}
                    </div>
                    <div class="card-footer card-footer-custom">
                        Total Unique Exhibitor who have ordered Extra requirements
                    </div>
                </div>
            </div>
        </div>
        <div class="row mb-4">
            <div class="col-md-12">
                <h3>Active Exhibitor Portal Users</h3>
                <div class="card">
                    <div class="card-body">
                        <p>Exhibitor Portal users are those who have logged in at least once.</p>
                        <p>
                            <span class="badge bg-success fs-5 px-3 py-2">
                                Total Active Users: {{ $activeExhibitorUsers }}
                            </span>
                        </p>
                        <p>
                            <span class="badge bg-danger fs-5 px-3 py-2">
                                Total Inactive Users: {{ $usersWithPaidApps - $activeExhibitorUsers }}
                            </span>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="row mb-4">
            <div class="col-md-4">
                <div class="card card-custom">
                    <div class="card-header card-header-custom">
                        Bare Space Applications
                    </div>
                    <div class="card-body card-body-custom bg-success-custom">
                        {{ $stallTypeCounts['bare_space_count'] ?? 0 }}
                    </div>
                    <div class="card-footer card-footer-custom">
                        Total Exhibitor Applications with Bare Space
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card card-custom">
                    <div class="card-header card-header-custom">
                        Shell Scheme Applications
                    </div>
                    <div class="card-body card-body-custom bg-pink">
                        {{ $stallTypeCounts['shell_scheme_count'] ?? 0 }}
                    </div>
                    <div class="card-footer card-footer-custom">
                        Total Exhibitor Applications with Shell Scheme
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card card-custom">
                    <div class="card-header card-header-custom">
                        All Stall Categories
                    </div>
                    <div class="card-body card-body-custom bg-dark-custom">
                        {{ ($stallTypeCounts['bare_space_count'] ?? 0) + ($stallTypeCounts['shell_scheme_count'] ?? 0) }}
                    </div>
                    <div class="card-footer card-footer-custom">
                        Total Applications (All Stall Categories)
                    </div>
                </div>
            </div>
        </div>

        {{-- @dd($shellCount) --}}
        <div class="row mb-4">
            <div class="col-md-6">
                <div class="card card-custom">
                    <div class="card-header card-header-custom">
                        Shell Scheme Applications with Fascia Name Filled
                    </div>
                    <div class="card-body card-body-custom bg-success-custom">
                        <form method="POST" action="{{ route('export.fascia') }}">
                            @csrf
                            <button type="submit" class="card-body card-body-custom "
                                style="border:none;width:100%;background:none;cursor:pointer;">
                                {{ $shellCount['fascia_filled_count'] ?? 0 }}
                            </button>
                        </form>
                    </div>
                    <div class="card-footer card-footer-custom">
                        Number of approved Shell Scheme applications with Fascia Name provided
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card card-custom">
                    <div class="card-header card-header-custom">
                        Shell Scheme Applications without Fascia Name
                    </div>
                    <div class="card-body card-body-custom bg-danger-custom">
                        {{ $shellCount['fascia_not_filled_count'] ?? 0 }}
                    </div>
                    <div class="card-footer card-footer-custom">
                        Number of approved Shell Scheme applications missing Fascia Name
                    </div>
                </div>
            </div>
        </div>

        {{-- Logo Uploaded COunt --}}
        <div class="row mb-4">
            <div class="col-md-6">
                <div class="card card-custom">
                    <div class="card-header card-header-custom">
                        Logo Uploaded Count
                    </div>
                    <div class="card-body card-body-custom bg-success-custom">
                        <form method="POST" action="{{ route('export.fasciaLogo') }}">
                            @csrf
                            <button type="submit" class="card-body card-body-custom bg-success-custom"
                                style="border:none;width:100%;background:none;cursor:pointer;">
                                {{ $logoCount ?? 0 }}
                            </button>
                        </form>
                    </div>
                    <div class="card-footer card-footer-custom">
                        Number of Exhibitors who have uploaded their logo
                    </div>
                </div>
            </div>
        </div>



        {{-- <h4>Exhibitor Pass Consumption</h4>
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th>Company Name</th>
                        <th>Stall Manning Used</th>
                        <th>Complimentary Passes Used</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($participantStats as $stat)
                        @php
                            //if stall_manning_used & complimentary_passes_used both are 0, skip the row
                            if ($stat['stall_manning_used'] == 0 && $stat['complimentary_passes_used'] == 0) {
                                continue;
                            }
                        @endphp
                        <tr>
                            <td>{{ $stat['company_name'] }}</td>
                            <td>{{ $stat['stall_manning_used'] }}</td>
                            <td>{{ $stat['complimentary_passes_used'] }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <h4>Applications with Invitation Letters</h4> --}}
        {{-- <ul>
        @foreach ($applicationsWithInvitation as $app)
            <li>{{ $app->company_name }} (ID: {{ $app->id }})</li>
        @endforeach
    </ul> --}}
    </div>
@endsection
