<?php 
require_once 'dbcon.php';

$conn = $link;

//get all the users stored in the database and decrypt the password generated by laravel 

$sql = "SELECT * FROM users";
$result = $conn->query($sql);

if ($result->num_rows > 0) {
    // output data of each row
    while($row = $result->fetch_assoc()) {
        echo "id: " . $row["id"]. " - Name: " . $row["name"]. " - Email: " . $row["email"]. " - Password: " . decrypt($row["password"]). "<br>";
    }
} else {
    echo "0 results";
}
$conn->close();

/**
 * Laravel stores passwords as hashes (bcrypt), not encrypted text.
 * Hashes are one-way and cannot be decrypted back to plain text.
 * There is NO way to retrieve the original password from the hash.
 * You can only check if a given password matches the hash using password_verify().
 * If you need to verify a password, use:
 * password_verify($inputPassword, $hashedPassword);
 */
function decrypt($data) {
    return 'Original password cannot be retrieved from Laravel hash';
}